package project.senior.holdit.model;

import java.util.ArrayList;

public class AddrList {
    int postcode;
    String province;
    String district;

    public AddrList() {
    }

    public AddrList(int postcode, String district, String province ) {
        this.province = province;
        this.district = district;
        this.postcode = postcode;
    }

    public ArrayList<AddrList> getAddrList(){
        ArrayList<AddrList> list = new ArrayList<>();
        list.add(new AddrList(37210,"ชานุมาน","อำนาจเจริญ"));
        list.add(new AddrList(37000,"เมืองอำนาจเจริญ","อำนาจเจริญ"));
        list.add(new AddrList(37180,"พนา","อำนาจเจริญ"));
        list.add(new AddrList(37290,"เสนางคนิคม","อำนาจเจริญ"));
        list.add(new AddrList(37240,"หัวตะพาน","อำนาจเจริญ"));
        list.add(new AddrList(37110,"ปทุมราชวงศา","อำนาจเจริญ"));
        list.add(new AddrList(14140,"ไชโย","อ่างทอง"));
        list.add(new AddrList(14130,"ป่าโมก","อ่างทอง"));
        list.add(new AddrList(14160,"สามโก้","อ่างทอง"));
        list.add(new AddrList(14110,"วิเศษชัยชาญ","อ่างทอง"));
        list.add(new AddrList(14000,"เมืองอ่างทอง","อ่างทอง"));
        list.add(new AddrList(14120,"โพธิ์ทอง","อ่างทอง"));
        list.add(new AddrList(14150,"แสวงหา","อ่างทอง"));
        list.add(new AddrList(10230,"คันนายาว","กรุงเทพมหานคร"));
        list.add(new AddrList(10600,"คลองสาน","กรุงเทพมหานคร"));
        list.add(new AddrList(10300,"ดุสิต","กรุงเทพมหานคร"));
        list.add(new AddrList(10240,"บางกะปิ","กรุงเทพมหานคร"));
        list.add(new AddrList(10220,"บางเขน","กรุงเทพมหานคร"));
        list.add(new AddrList(10150,"บางขุนเทียน","กรุงเทพมหานคร"));
        list.add(new AddrList(10150,"บางบอน","กรุงเทพมหานคร"));
        list.add(new AddrList(10160,"บางแค","กรุงเทพมหานคร"));
        list.add(new AddrList(10120,"บางคอแหลม","กรุงเทพมหานคร"));
        list.add(new AddrList(10700,"บางพลัด","กรุงเทพมหานคร"));
        list.add(new AddrList(10800,"บางซื่อ","กรุงเทพมหานคร"));
        list.add(new AddrList(10600,"บางกอกใหญ่","กรุงเทพมหานคร"));
        list.add(new AddrList(10500,"บางรัก","กรุงเทพมหานคร"));
        list.add(new AddrList(10260,"บางนา","กรุงเทพมหานคร"));
        list.add(new AddrList(10700,"บางกอกน้อย","กรุงเทพมหานคร"));
        list.add(new AddrList(10240,"บึงกุ่ม","กรุงเทพมหานคร"));
        list.add(new AddrList(10520,"ลาดกระบัง","กรุงเทพมหานคร"));
        list.add(new AddrList(10510,"Min Buri","กรุงเทพมหานคร"));
        list.add(new AddrList(10260,"พระโขนง","กรุงเทพมหานคร"));
        list.add(new AddrList(10160,"หนองแขม","กรุงเทพมหานคร"));
        list.add(new AddrList(10160,"ภาษีเจริญ","กรุงเทพมหานคร"));
        list.add(new AddrList(10100,"สัมพันธวงศ์","กรุงเทพมหานคร"));
        list.add(new AddrList(10100,"ป้อมปราบศัตรูพ่าย","กรุงเทพมหานคร"));
        list.add(new AddrList(10140,"ราษฎร์บูรณะ","กรุงเทพมหานคร"));
        list.add(new AddrList(10140,"ทุ่งครุ","กรุงเทพมหานคร"));
        list.add(new AddrList(10230,"ลาดพร้าว","กรุงเทพมหานคร"));
        list.add(new AddrList(10240,"สะพานสูง","กรุงเทพมหานคร"));
        list.add(new AddrList(10250,"สวนหลวง","กรุงเทพมหานคร"));
        list.add(new AddrList(10170,"ทวีวัฒนา","กรุงเทพมหานคร"));
        list.add(new AddrList(10110,"วัฒนา","กรุงเทพมหานคร"));
        list.add(new AddrList(10400,"ดินแดง","กรุงเทพมหานคร"));
        list.add(new AddrList(10320,"ห้วยขวาง","กรุงเทพมหานคร"));
        list.add(new AddrList(10510,"คลองสามวา","กรุงเทพมหานคร"));
        list.add(new AddrList(10210,"หลักสี่","กรุงเทพมหานคร"));
        list.add(new AddrList(10530,"หนองจอก","กรุงเทพมหานคร"));
        list.add(new AddrList(10330,"ปทุมวัน","กรุงเทพมหานคร"));
        list.add(new AddrList(10400,"พญาไท","กรุงเทพมหานคร"));
        list.add(new AddrList(10200,"พระนคร","กรุงเทพมหานคร"));
        list.add(new AddrList(10250,"ประเวศ","กรุงเทพมหานคร"));
        list.add(new AddrList(10220,"สายไหม","กรุงเทพมหานคร"));
        list.add(new AddrList(10170,"ตลิ่งชัน","กรุงเทพมหานคร"));
        list.add(new AddrList(10600,"ธนบุรี","กรุงเทพมหานคร"));
        list.add(new AddrList(10310,"วังทองหลาง","กรุงเทพมหานคร"));
        list.add(new AddrList(10120,"ยานนาวา","กรุงเทพมหานคร"));
        list.add(new AddrList(31180,"บ้านกรวด","บุรีรัมย์"));
        list.add(new AddrList(31250,"พลับพลาชัย","บุรีรัมย์"));
        list.add(new AddrList(31120,"บ้านใหม่ไชยพจน์","บุรีรัมย์"));
        list.add(new AddrList(31110,"เฉลิมพระเกียรติ","บุรีรัมย์"));
        list.add(new AddrList(31110,"ชำนิ","บุรีรัมย์"));
        list.add(new AddrList(31000,"บ้านด่าน","บุรีรัมย์"));
        list.add(new AddrList(31000,"ห้วยราช","บุรีรัมย์"));
        list.add(new AddrList(31150,"แคนดง","บุรีรัมย์"));
        list.add(new AddrList(31190,"คูเมือง","บุรีรัมย์"));
        list.add(new AddrList(31160,"กระสัง","บุรีรัมย์"));
        list.add(new AddrList(31170,"ละหานทราย","บุรีรัมย์"));
        list.add(new AddrList(31130,"ลำปลายมาศ","บุรีรัมย์"));
        list.add(new AddrList(31000,"เมืองบุรีรัมย์","บุรีรัมย์"));
        list.add(new AddrList(31230,"นาโพธิ์","บุรีรัมย์"));
        list.add(new AddrList(31110,"นางรอง","บุรีรัมย์"));
        list.add(new AddrList(31260,"โนนดินแดง","บุรีรัมย์"));
        list.add(new AddrList(31110,"โนนสุวรรณ","บุรีรัมย์"));
        list.add(new AddrList(31240,"หนองหงส์","บุรีรัมย์"));
        list.add(new AddrList(31210,"หนองกี่","บุรีรัมย์"));
        list.add(new AddrList(31220,"ปะคำ","บุรีรัมย์"));
        list.add(new AddrList(31120,"พุทไธสง","บุรีรัมย์"));
        list.add(new AddrList(31140,"ประโคนชัย","บุรีรัมย์"));
        list.add(new AddrList(31150,"สตึก","บุรีรัมย์"));
        list.add(new AddrList(24140,"บ้านโพธิ์","ฉะเชิงเทรา"));
        list.add(new AddrList(24110,"บางคล้า","ฉะเชิงเทรา"));
        list.add(new AddrList(24150,"บางน้ำเปรี้ยว","ฉะเชิงเทรา"));
        list.add(new AddrList(24130,"บางปะกง","ฉะเชิงเทรา"));
        list.add(new AddrList(24000,"คลองเขื่อน","ฉะเชิงเทรา"));
        list.add(new AddrList(24000,"เมืองฉะเชิงเทรา","ฉะเชิงเทรา"));
        list.add(new AddrList(24190,"แปลงยาว","ฉะเชิงเทรา"));
        list.add(new AddrList(24120,"พนมสารคาม","ฉะเชิงเทรา"));
        list.add(new AddrList(24120,"ราชสาส์น","ฉะเชิงเทรา"));
        list.add(new AddrList(24160,"สนามชัยเขต","ฉะเชิงเทรา"));
        list.add(new AddrList(24160,"ท่าตะเกียบ","ฉะเชิงเทรา"));
        list.add(new AddrList(17130,"หันคา","ชัยนาท"));
        list.add(new AddrList(17110,"มโนรมย์","ชัยนาท"));
        list.add(new AddrList(17000,"เมืองชัยนาท","ชัยนาท"));
        list.add(new AddrList(17130,"เนินขาม","ชัยนาท"));
        list.add(new AddrList(17100,"หนองมะโมง","ชัยนาท"));
        list.add(new AddrList(17140,"สรรคบุรี","ชัยนาท"));
        list.add(new AddrList(17150,"สรรพยา","ชัยนาท"));
        list.add(new AddrList(17120,"วัดสิงห์","ชัยนาท"));
        list.add(new AddrList(36160,"บำเหน็จณรงค์","ชัยภูมิ"));
        list.add(new AddrList(36170,"บ้านเขว้า","ชัยภูมิ"));
        list.add(new AddrList(36190,"บ้านแท่น","ชัยภูมิ"));
        list.add(new AddrList(36130,"จัตุรัส","ชัยภูมิ"));
        list.add(new AddrList(36150,"แก้งคร้อ","ชัยภูมิ"));
        list.add(new AddrList(36120,"เกษตรสมบูรณ์","ชัยภูมิ"));
        list.add(new AddrList(36180,"คอนสาร","ชัยภูมิ"));
        list.add(new AddrList(36140,"คอนสวรรค์","ชัยภูมิ"));
        list.add(new AddrList(36000,"เมืองชัยภูมิ","ชัยภูมิ"));
        list.add(new AddrList(36130,"เนินสง่า","ชัยภูมิ"));
        list.add(new AddrList(36210,"หนองบัวแดง","ชัยภูมิ"));
        list.add(new AddrList(36250,"หนองบัวระเหว","ชัยภูมิ"));
        list.add(new AddrList(36260,"ภักดีชุมพล","ชัยภูมิ"));
        list.add(new AddrList(36110,"ภูเขียว","ชัยภูมิ"));
        list.add(new AddrList(36130,"ซับใหญ่","ชัยภูมิ"));
        list.add(new AddrList(36230,"เทพสถิต","ชัยภูมิ"));
        list.add(new AddrList(22160,"แก่งหางแมว","จันทบุรี"));
        list.add(new AddrList(22210,"เขาคิชฌกูฏ","จันทบุรี"));
        list.add(new AddrList(22110,"ขลุง","จันทบุรี"));
        list.add(new AddrList(22130,"แหลมสิงห์","จันทบุรี"));
        list.add(new AddrList(22150,"มะขาม","จันทบุรี"));
        list.add(new AddrList(22000,"เมืองจันทบุรี","จันทบุรี"));
        list.add(new AddrList(22160,"นายายอาม","จันทบุรี"));
        list.add(new AddrList(22140,"โป่งน้ำร้อน","จันทบุรี"));
        list.add(new AddrList(22180,"สอยดาว","จันทบุรี"));
        list.add(new AddrList(22120,"ท่าใหม่","จันทบุรี"));
        list.add(new AddrList(50320,"ไชยปราการ","เชียงใหม่"));
        list.add(new AddrList(50170,"เชียงดาว","เชียงใหม่"));
        list.add(new AddrList(50160,"จอมทอง","เชียงใหม่"));
        list.add(new AddrList(50160,"ดอยหล่อ","เชียงใหม่"));
        list.add(new AddrList(50220,"ดอยสะเก็ด","เชียงใหม่"));
        list.add(new AddrList(50260,"ดอยเต่า","เชียงใหม่"));
        list.add(new AddrList(50110,"ฝาง","เชียงใหม่"));
        list.add(new AddrList(50230,"หางดง","เชียงใหม่"));
        list.add(new AddrList(50240,"ฮอด","เชียงใหม่"));
        list.add(new AddrList(50280,"แม่อาย","เชียงใหม่"));
        list.add(new AddrList(50270,"แม่แจ่ม","เชียงใหม่"));
        list.add(new AddrList(50130,"แม่ออน","เชียงราย"));
        list.add(new AddrList(50180,"แม่ริม","เชียงใหม่"));
        list.add(new AddrList(50150,"แม่แตง","เชียงใหม่"));
        list.add(new AddrList(50360,"แม่วาง","เชียงใหม่"));
        list.add(new AddrList(50000,"เมืองเชียงใหม่","เชียงใหม่"));
        list.add(new AddrList(50310,"อมก๋อย","เชียงใหม่"));
        list.add(new AddrList(50190,"พร้าว","เชียงใหม่"));
        list.add(new AddrList(50250,"สะเมิง","เชียงใหม่"));
        list.add(new AddrList(50130,"สันกำแพง","เชียงใหม่"));
        list.add(new AddrList(50120,"สันป่าตอง","เชียงใหม่"));
        list.add(new AddrList(50210,"สันทราย","เชียงใหม่"));
        list.add(new AddrList(50140,"สารภี","เชียงใหม่"));
        list.add(new AddrList(50350,"เวียงแหง","เชียงใหม่"));
        list.add(new AddrList(57140,"เชียงของ","เชียงราย"));
        list.add(new AddrList(57150,"เชียงแสน","เชียงราย"));
        list.add(new AddrList(57110,"ดอยหลวง","เชียงราย"));
        list.add(new AddrList(57340,"ขุนตาล","เชียงราย"));
        list.add(new AddrList(57110,"แม่จัน","เชียงราย"));
        list.add(new AddrList(57250,"แม่ลาว","เชียงราย"));
        list.add(new AddrList(57110,"แม่ฟ้าหลวง","เชียงราย"));
        list.add(new AddrList(57130,"แม่สาย","เชียงราย"));
        list.add(new AddrList(57180,"แม่สรวย","เชียงราย"));
        list.add(new AddrList(57000,"เมืองเชียงราย","เชียงราย"));
        list.add(new AddrList(57190,"ป่าแดด","เชียงราย"));
        list.add(new AddrList(57120,"พาน","เชียงราย"));
        list.add(new AddrList(57290,"พญาเม็งราย","เชียงราย"));
        list.add(new AddrList(57160,"เทิง","เชียงราย"));
        list.add(new AddrList(57210,"เวียงชัย","เชียงราย"));
        list.add(new AddrList(57210,"เวียงเชียงรุ้ง","เชียงราย"));
        list.add(new AddrList(57310,"เวียงแก่น","เชียงราย"));
        list.add(new AddrList(57170,"เวียงป่าเป้า","เชียงราย"));
        list.add(new AddrList(20170,"บ้านบึง","ชลบุรี"));
        list.add(new AddrList(20150,"บางละมุง","ชลบุรี"));
        list.add(new AddrList(20270,"บ่อทอง","ชลบุรี"));
        list.add(new AddrList(20240,"เกาะจันทร์","ชลบุรี"));
        list.add(new AddrList(20120,"เกาะสีชัง","ชลบุรี"));
        list.add(new AddrList(20000,"เมืองชลบุรี","ชลบุรี"));
        list.add(new AddrList(20190,"หนองใหญ่","ชลบุรี"));
        list.add(new AddrList(20160,"พานทอง","ชลบุรี"));
        list.add(new AddrList(20140,"พนัสนิคม","ชลบุรี"));
        list.add(new AddrList(20180,"สัตหีบ","ชลบุรี"));
        list.add(new AddrList(20110,"ศรีราชา","ชลบุรี"));
        list.add(new AddrList(86170,"ละแม","ชุมพร"));
        list.add(new AddrList(86110,"หลังสวน","ชุมพร"));
        list.add(new AddrList(86000,"เมืองชุมพร","ชุมพร"));
        list.add(new AddrList(86160,"ปะทิว","ชุมพร"));
        list.add(new AddrList(86180,"พะโต๊ะ","ชุมพร"));
        list.add(new AddrList(86130,"สวี","ชุมพร"));
        list.add(new AddrList(86140,"ท่าแซะ","ชุมพร"));
        list.add(new AddrList(86220,"ทุ่งตะโก","ชุมพร"));
        list.add(new AddrList(46000,"ดอนจาน","กาฬสินธุ์"));
        list.add(new AddrList(46170,"ห้วยเม็ก","กาฬสินธุ์"));
        list.add(new AddrList(46240,"ห้วยผึ้ง","กาฬสินธุ์"));
        list.add(new AddrList(46130,"กมลาไสย","กาฬสินธุ์"));
        list.add(new AddrList(46180,"คำม่วง","กาฬสินธุ์"));
        list.add(new AddrList(46160,"เขาวง","กาฬสินธุ์"));
        list.add(new AddrList(46130,"ฆ้องชัย","กาฬสินธุ์"));
        list.add(new AddrList(46110,"กุฉินารายณ์","กาฬสินธุ์"));
        list.add(new AddrList(46000,"เมืองกาฬสินธุ์","กาฬสินธุ์"));
        list.add(new AddrList(46160,"นาคู","กาฬสินธุ์"));
        list.add(new AddrList(46230,"นามน","กาฬสินธุ์"));
        list.add(new AddrList(46220,"หนองกุงศรี","กาฬสินธุ์"));
        list.add(new AddrList(46210,"ร่องคำ","กาฬสินธุ์"));
        list.add(new AddrList(46140,"สหัสขันธ์","กาฬสินธุ์"));
        list.add(new AddrList(46150,"สมเด็จ","กาฬสินธุ์"));
        list.add(new AddrList(46190,"ท่าคันโท","กาฬสินธุ์"));
        list.add(new AddrList(46120,"ยางตลาด","กาฬสินธุ์"));
        list.add(new AddrList(62210,"บึงสามัคคี","กำแพงเพชร"));
        list.add(new AddrList(62130,"ขาณุวรลักษบุรี","กำแพงเพชร"));
        list.add(new AddrList(62120,"คลองขลุง","กำแพงเพชร"));
        list.add(new AddrList(62180,"คลองลาน","กำแพงเพชร"));
        list.add(new AddrList(62170,"โกสัมพีนคร","กำแพงเพชร"));
        list.add(new AddrList(62170,"ลานกระบือ","กำแพงเพชร"));
        list.add(new AddrList(62000,"เมืองกำแพงเพชร","กำแพงเพชร"));
        list.add(new AddrList(62120,"ปางศิลาทอง","กำแพงเพชร"));
        list.add(new AddrList(62110,"พรานกระต่าย","กำแพงเพชร"));
        list.add(new AddrList(62150,"ไทรงาม","กำแพงเพชร"));
        list.add(new AddrList(62190,"ทรายทองวัฒนา","กำแพงเพชร"));
        list.add(new AddrList(71160,"บ่อพลอย","กาญจนบุรี"));
        list.add(new AddrList(71260,"ด่านมะขามเตี้ย","กาญจนบุรี"));
        list.add(new AddrList(71170,"ห้วยกระเจา","กาญจนบุรี"));
        list.add(new AddrList(71210,"เลาขวัญ","กาญจนบุรี"));
        list.add(new AddrList(71000,"เมืองกาญจนบุรี","กาญจนบุรี"));
        list.add(new AddrList(71220,"หนองปรือ","กาญจนบุรี"));
        list.add(new AddrList(71140,"พนมทวน","กาญจนบุรี"));
        list.add(new AddrList(71150,"ไทรโยค","กาญจนบุรี"));
        list.add(new AddrList(71240,"สังขละบุรี","กาญจนบุรี"));
        list.add(new AddrList(71250,"ศรีสวัสดิ์","กาญจนบุรี"));
        list.add(new AddrList(71120,"ท่ามะกา","กาญจนบุรี"));
        list.add(new AddrList(71110,"ท่าม่วง","กาญจนบุรี"));
        list.add(new AddrList(71180,"ทองผาภูมิ","กาญจนบุรี"));
        list.add(new AddrList(40270,"บ้านฝาง","ขอนแก่น"));
        list.add(new AddrList(40110,"บ้านแฮด","ขอนแก่น"));
        list.add(new AddrList(40110,"บ้านไผ่","ขอนแก่น"));
        list.add(new AddrList(40180,"ชนบท","ขอนแก่น"));
        list.add(new AddrList(40130,"ชุมแพ","ขอนแก่น"));
        list.add(new AddrList(40280,"เขาสวนกวาง","ขอนแก่น"));
        list.add(new AddrList(40160,"โคกโพธิ์ไชย","ขอนแก่น"));
        list.add(new AddrList(40170,"กระนวน","ขอนแก่น"));
        list.add(new AddrList(40160,"มัญจาคีรี","ขอนแก่น"));
        list.add(new AddrList(40000,"เมืองขอนแก่น","ขอนแก่น"));
        list.add(new AddrList(40140,"น้ำพอง","ขอนแก่น"));
        list.add(new AddrList(40110,"โนนศิลา","ขอนแก่น"));
        list.add(new AddrList(40150,"หนองนาคำ","ขอนแก่น"));
        list.add(new AddrList(40210,"หนองเรือ","ขอนแก่น"));
        list.add(new AddrList(40190,"หนองสองห้อง","ขอนแก่น"));
        list.add(new AddrList(40120,"พล","ขอนแก่น"));
        list.add(new AddrList(40320,"พระยืน","ขอนแก่น"));
        list.add(new AddrList(40350,"ภูผาม่าน","ขอนแก่น"));
        list.add(new AddrList(40150,"ภูเวียง","ขอนแก่น"));
        list.add(new AddrList(40340,"เปือยน้อย","ขอนแก่น"));
        list.add(new AddrList(40220,"สีชมพู","ขอนแก่น"));
        list.add(new AddrList(40170,"ซำสูง","ขอนแก่น"));
        list.add(new AddrList(40250,"อุบลรัตน์","ขอนแก่น"));
        list.add(new AddrList(40230,"แวงน้อย","ขอนแก่น"));
        list.add(new AddrList(40330,"แวงใหญ่","ขอนแก่น"));
        list.add(new AddrList(81110,"อ่าวลึก","กระบี่"));
        list.add(new AddrList(81140,"เขาพนม","กระบี่"));
        list.add(new AddrList(81120,"คลองท่อม","กระบี่"));
        list.add(new AddrList(81150,"เกาะลันตา","กระบี่"));
        list.add(new AddrList(81120,"ลำทับ","กระบี่"));
        list.add(new AddrList(81000,"เมืองกระบี่","กระบี่"));
        list.add(new AddrList(81130,"เหนือคลอง","กระบี่"));
        list.add(new AddrList(81160,"ปลายพระยา","กระบี่"));
        list.add(new AddrList(52120,"แจ้ห่ม","ลำปาง"));
        list.add(new AddrList(52190,"ห้างฉัตร","ลำปาง"));
        list.add(new AddrList(52130,"เกาะคา","ลำปาง"));
        list.add(new AddrList(52220,"แม่เมาะ","ลำปาง"));
        list.add(new AddrList(52180,"แม่พริก","ลำปาง"));
        list.add(new AddrList(52150,"แม่ทะ","ลำปาง"));
        list.add(new AddrList(52000,"เมืองลำปาง","ลำปาง"));
        list.add(new AddrList(52240,"เมืองปาน","ลำปาง"));
        list.add(new AddrList(52110,"งาว","ลำปาง"));
        list.add(new AddrList(52210,"เสริมงาม","ลำปาง"));
        list.add(new AddrList(52170,"สบปราบ","ลำปาง"));
        list.add(new AddrList(52160,"เถิน","ลำปาง"));
        list.add(new AddrList(52140,"วังเหนือ","ลำปาง"));
        list.add(new AddrList(51130,"Ban Hong","ลำพูน"));
        list.add(new AddrList(51180,"Ban Thi","ลำพูน"));
        list.add(new AddrList(51110,"Li","ลำพูน"));
        list.add(new AddrList(51140,"Mae Tha","ลำพูน"));
        list.add(new AddrList(51000,"เมืองลำพูน","ลำพูน"));
        list.add(new AddrList(51120,"Pa Sang","ลำพูน"));
        list.add(new AddrList(51160,"Thung Hua Chang","ลำพูน"));
        list.add(new AddrList(51120,"Wiang Nonglong","ลำพูน"));
        list.add(new AddrList(42110,"Chiang Khan","เลย"));
        list.add(new AddrList(42120,"Dan Sai","เลย"));
        list.add(new AddrList(41220,"Erawan","เลย"));
        list.add(new AddrList(42000,"เมืองเลย","เลย"));
        list.add(new AddrList(42210,"Na Duang","เลย"));
        list.add(new AddrList(42170,"Na Haeo","เลย"));
        list.add(new AddrList(42150,"Pak Chom","เลย"));
        list.add(new AddrList(42240,"Pha Khao","เลย"));
        list.add(new AddrList(42180,"Phu Kradung","เลย"));
        list.add(new AddrList(42230,"Phu Luang","เลย"));
        list.add(new AddrList(42160,"Phu Rua","เลย"));
        list.add(new AddrList(42140,"Tha Li","เลย"));
        list.add(new AddrList(42130,"Wang Saphung","เลย"));
        list.add(new AddrList(15110,"Ban Mi","ลพบุรี"));
        list.add(new AddrList(15130,"Chai Badan","ลพบุรี"));
        list.add(new AddrList(15250,"Khok Charoen","ลพบุรี"));
        list.add(new AddrList(15120,"Khok Samrong","ลพบุรี"));
        list.add(new AddrList(15190,"Lum Sunthi","ลพบุรี"));
        list.add(new AddrList(15000,"เมืองลพบุรี","ลพบุรี"));
        list.add(new AddrList(15170,"Nong Muang","ลพบุรี"));
        list.add(new AddrList(15140,"Phattana Nikhom","ลพบุรี"));
        list.add(new AddrList(15240,"Sa Bot","ลพบุรี"));
        list.add(new AddrList(15130,"Tha Luang","ลพบุรี"));
        list.add(new AddrList(15150,"Tha Wung","ลพบุรี"));
        list.add(new AddrList(58140,"Khun Yuam","แม่ฮ่องสอน"));
        list.add(new AddrList(58120,"Mae La Noi","แม่ฮ่องสอน"));
        list.add(new AddrList(58110,"Mae Sariang","แม่ฮ่องสอน"));
        list.add(new AddrList(58000,"เมืองแม่ฮ่องสอน","แม่ฮ่องสอน"));
        list.add(new AddrList(58130,"Pai","แม่ฮ่องสอน"));
        list.add(new AddrList(58150,"Pang Mapha","แม่ฮ่องสอน"));
        list.add(new AddrList(58110,"Sop Moei","แม่ฮ่องสอน"));
        list.add(new AddrList(44130,"Borabu","มหาสารคาม"));
        list.add(new AddrList(44160,"Chiang Yun","มหาสารคาม"));
        list.add(new AddrList(44160,"Chuan Chum","มหาสารคาม"));
        list.add(new AddrList(44190,"Kae Dam","มหาสารคาม"));
        list.add(new AddrList(44150,"Kantharawichai","มหาสารคาม"));
        list.add(new AddrList(44140,"Kosum Phisai","มหาสารคาม"));
        list.add(new AddrList(44130,"Kud Rang","มหาสารคาม"));
        list.add(new AddrList(44000,"เมืองมหาสารคาม","มหาสารคาม"));
        list.add(new AddrList(44170,"Na Chuak","มหาสารคาม"));
        list.add(new AddrList(44180,"Na Dun","มหาสารคาม"));
        list.add(new AddrList(44110,"Phayakkhaphum Phisai","มหาสารคาม"));
        list.add(new AddrList(44120,"Wapi Pathum","มหาสารคาม"));
        list.add(new AddrList(44210,"Yang Si Surat","มหาสารคาม"));
        list.add(new AddrList(49140,"Don Luang","มุกดาหาร"));
        list.add(new AddrList(49120,"Don Tan","มุกดาหาร"));
        list.add(new AddrList(49110,"Khamcha-I","มุกดาหาร"));
        list.add(new AddrList(49000,"เมืองมุกดาหาร","มุกดาหาร"));
        list.add(new AddrList(49130,"Nikhom Kham Soi","มุกดาหาร"));
        list.add(new AddrList(49160,"Nong Sung","มุกดาหาร"));
        list.add(new AddrList(49150,"Wan Yai","มุกดาหาร"));
        list.add(new AddrList(26110,"Ban Na","นครนายก"));
        list.add(new AddrList(26000,"เมืองนครนายก","นครนายก"));
        list.add(new AddrList(26120,"Ongkarak","นครนายก"));
        list.add(new AddrList(26130,"Pak Phli","นครนายก"));
        list.add(new AddrList(73130,"Bang Len","นครปฐม"));
        list.add(new AddrList(73150,"Don Tum","นครปฐม"));
        list.add(new AddrList(73140,"Khamphaeng Saen","นครปฐม"));
        list.add(new AddrList(73000,"เมืองนครปฐม","นครปฐม"));
        list.add(new AddrList(73120,"Nakhon Chaisi","นครปฐม"));
        list.add(new AddrList(73170,"Phutha Monthon","นครปฐม"));
        list.add(new AddrList(73110,"Sam Phran","นครปฐม"));
        list.add(new AddrList(48140,"Ban Phaeng","นครพนม"));
        list.add(new AddrList(48000,"เมืองนครพนม","นครพนม"));
        list.add(new AddrList(48130,"Na Kae","นครพนม"));
        list.add(new AddrList(48140,"Na Thom","นครพนม"));
        list.add(new AddrList(48180,"Na Wa","นครพนม"));
        list.add(new AddrList(48190,"Phon Sawan","นครพนม"));
        list.add(new AddrList(48160,"Pla Pak","นครพนม"));
        list.add(new AddrList(48170,"Renu Nakhon","นครพนม"));
        list.add(new AddrList(48150,"Si Songkhram","นครพนม"));
        list.add(new AddrList(48120,"Tha Songkhram","นครพนม"));
        list.add(new AddrList(48120,"Tha Uthen","นครพนม"));
        list.add(new AddrList(48110,"That Phanom","นครพนม"));
        list.add(new AddrList(48130,"Wang Yang","นครพนม"));
        list.add(new AddrList(30350,"Ban Luam","นครราชสีมา"));
        list.add(new AddrList(30120,"Bua Lai","นครราชสีมา"));
        list.add(new AddrList(30120,"Bua Yai","นครราชสีมา"));
        list.add(new AddrList(30230,"Chakkarat","นครราชสีมา"));
        list.add(new AddrList(30230,"Cheleam Phakiat","นครราชสีมา"));
        list.add(new AddrList(30190,"Chok Chai","นครราชสีมา"));
        list.add(new AddrList(30270,"Chum Phuang","นครราชสีมา"));
        list.add(new AddrList(30210,"Dan Khun Thot","นครราชสีมา"));
        list.add(new AddrList(30240,"Huai Thalaeng","นครราชสีมา"));
        list.add(new AddrList(30440,"Kang Sanam น่านg","นครราชสีมา"));
        list.add(new AddrList(30290,"Kham Sakae Saeng","นครราชสีมา"));
        list.add(new AddrList(30280,"Kham Thale So","นครราชสีมา"));
        list.add(new AddrList(30250,"Khon Buri","นครราชสีมา"));
        list.add(new AddrList(30260,"Khong","นครราชสีมา"));
        list.add(new AddrList(30270,"Lum Thamenchai","นครราชสีมา"));
        list.add(new AddrList(30000,"เมืองนครราชสีมา","นครราชสีมา"));
        list.add(new AddrList(30270,"เมืองYang","นครราชสีมา"));
        list.add(new AddrList(30360,"Non Daeng","นครราชสีมา"));
        list.add(new AddrList(30160,"Non Sung","นครราชสีมา"));
        list.add(new AddrList(30220,"Non Thai","นครราชสีมา"));
        list.add(new AddrList(30410,"Nong Bunnak","นครราชสีมา"));
        list.add(new AddrList(30130,"Pak Chong","นครราชสีมา"));
        list.add(new AddrList(30150,"Pak Thong Chai","นครราชสีมา"));
        list.add(new AddrList(30110,"Phimai","นครราชสีมา"));
        list.add(new AddrList(30220,"Phra Thomgkom","นครราชสีมา"));
        list.add(new AddrList(30180,"Prathai","นครราชสีมา"));
        list.add(new AddrList(30430,"Sida","นครราชสีมา"));
        list.add(new AddrList(30140,"Sikhiu","นครราชสีมา"));
        list.add(new AddrList(30330,"Soeng Sang","นครราชสีมา"));
        list.add(new AddrList(30170,"Sung Noen","นครราชสีมา"));
        list.add(new AddrList(30210,"Theparak","นครราชสีมา"));
        list.add(new AddrList(30370,"Wang Nam Khyo","นครราชสีมา"));
        list.add(new AddrList(60180,"Banphot Phisai","นครสวรรค์"));
        list.add(new AddrList(60150,"Chum Tabong","นครสวรรค์"));
        list.add(new AddrList(60120,"Chumsaeng","นครสวรรค์"));
        list.add(new AddrList(60230,"Kao Lieo","นครสวรรค์"));
        list.add(new AddrList(60170,"Krok Phra","นครสวรรค์"));
        list.add(new AddrList(60150,"Lat Yao","นครสวรรค์"));
        list.add(new AddrList(60150,"Mae Poen","นครสวรรค์"));
        list.add(new AddrList(60150,"Mae Wong","นครสวรรค์"));
        list.add(new AddrList(60000,"เมืองนครสวรรค์","นครสวรรค์"));
        list.add(new AddrList(60110,"Nong Bua","นครสวรรค์"));
        list.add(new AddrList(60220,"Phaisali","นครสวรรค์"));
        list.add(new AddrList(60130,"Phayuha Khiri","นครสวรรค์"));
        list.add(new AddrList(60190,"ตาก Fa","นครสวรรค์"));
        list.add(new AddrList(60140,"ตากhli","นครสวรรค์"));
        list.add(new AddrList(60160,"Tha ตากo","นครสวรรค์"));
        list.add(new AddrList(80360,"Bang Khan","นครศรีธรรมราช"));
        list.add(new AddrList(80180,"Cha-Uat","นครศรีธรรมราช"));
        list.add(new AddrList(80190,"Chaloem Phrakiat","นครศรีธรรมราช"));
        list.add(new AddrList(80250,"Chang Khlang","นครศรีธรรมราช"));
        list.add(new AddrList(80150,"Chang Khlang","นครศรีธรรมราช"));
        list.add(new AddrList(80190,"Chian Yai","นครศรีธรรมราช"));
        list.add(new AddrList(80130,"Chula Phon","นครศรีธรรมราช"));
        list.add(new AddrList(80170,"Hua Sai","นครศรีธรรมราช"));
        list.add(new AddrList(80210,"Khanom","นครศรีธรรมราช"));
        list.add(new AddrList(84310,"Lamai Beach","นครศรีธรรมราช"));
        list.add(new AddrList(80230,"Lan Saka","นครศรีธรรมราช"));
        list.add(new AddrList(80000,"เมืองNakhon Si Thammarat","นครศรีธรรมราช"));
        list.add(new AddrList(80220,"Na Bon","นครศรีธรรมราช"));
        list.add(new AddrList(80160,"Nob Pitam","นครศรีธรรมราช"));
        list.add(new AddrList(80140,"Pak Phaน่านg","นครศรีธรรมราช"));
        list.add(new AddrList(80270,"Phipun","นครศรีธรรมราช"));
        list.add(new AddrList(80000,"Phra Phrom","นครศรีธรรมราช"));
        list.add(new AddrList(80320,"Phromkhiri","นครศรีธรรมราช"));
        list.add(new AddrList(80130,"Ron Phibun","นครศรีธรรมราช"));
        list.add(new AddrList(80120,"Sichon","นครศรีธรรมราช"));
        list.add(new AddrList(80160,"Tha Sala","นครศรีธรรมราช"));
        list.add(new AddrList(80260,"Tham Punnara","นครศรีธรรมราช"));
        list.add(new AddrList(80110,"Thung Song","นครศรีธรรมราช"));
        list.add(new AddrList(80240,"Thung Yai","นครศรีธรรมราช"));
        list.add(new AddrList(55190,"Ban Luang","น่าน"));
        list.add(new AddrList(55220,"Bo Klua","น่าน"));
        list.add(new AddrList(55130,"Chaloem Phrakiat","น่าน"));
        list.add(new AddrList(55160,"Chiang Klang","น่าน"));
        list.add(new AddrList(55170,"Mae Charim","น่าน"));
        list.add(new AddrList(55000,"เมืองน่าน","น่าน"));
        list.add(new AddrList(55180,"Na Mun","น่าน"));
        list.add(new AddrList(55150,"Na Noi","น่าน"));
        list.add(new AddrList(55000,"Phu Piang","น่าน"));
        list.add(new AddrList(55120,"Pua","น่าน"));
        list.add(new AddrList(55000,"Santisuk","น่าน"));
        list.add(new AddrList(55160,"Song Khaew","น่าน"));
        list.add(new AddrList(55140,"Tha Wang Pha","น่าน"));
        list.add(new AddrList(55130,"Thung Chang","น่าน"));
        list.add(new AddrList(55110,"Wiang Sa","น่าน"));
        list.add(new AddrList(96170,"Bacho","นราธิวาส"));
        list.add(new AddrList(96220,"Chanae","นราธิวาส"));
        list.add(new AddrList(96130,"Jao I Rong","นราธิวาส"));
        list.add(new AddrList(96000,"เมืองนราธิวาส","นราธิวาส"));
        list.add(new AddrList(96130,"Rangae","นราธิวาส"));
        list.add(new AddrList(96150,"Ruso","นราธิวาส"));
        list.add(new AddrList(96210,"Si Sakhon","นราธิวาส"));
        list.add(new AddrList(96190,"Sukhirin","นราธิวาส"));
        list.add(new AddrList(96120,"Sungai Kolok","นราธิวาส"));
        list.add(new AddrList(96140,"Sungai Padi","นราธิวาส"));
        list.add(new AddrList(96110,"ตาก Bai","นราธิวาส"));
        list.add(new AddrList(96160,"Waeng","นราธิวาส"));
        list.add(new AddrList(96180,"Yi-Ngo","นราธิวาส"));
        list.add(new AddrList(39000,"เมืองNong Bua Lam Phu","หนองบัวลำภู"));
        list.add(new AddrList(39170,"Na Klang","หนองบัวลำภู"));
        list.add(new AddrList(39170,"Nawang","หนองบัวลำภู"));
        list.add(new AddrList(39140,"Non Sang","หนองบัวลำภู"));
        list.add(new AddrList(39140,"Nong Sang","หนองบัวลำภู"));
        list.add(new AddrList(39180,"Si Bun Ruang","หนองบัวลำภู"));
        list.add(new AddrList(39270,"Suwannakhuha","หนองบัวลำภู"));
        list.add(new AddrList(43140,"Bung Kan","หนองคาย"));
        list.add(new AddrList(43220,"Bung Khong Long","หนองคาย"));
        list.add(new AddrList(43140,"Bung Kla","หนองคาย"));
        list.add(new AddrList(43120,"Fao Rai","หนองคาย"));
        list.add(new AddrList(43000,"เมืองหนองคาย","หนองคาย"));
        list.add(new AddrList(43190,"Pak Khat","หนองคาย"));
        list.add(new AddrList(43180,"Phon Charoen","หนองคาย"));
        list.add(new AddrList(43120,"Phon Phisai","หนองคาย"));
        list.add(new AddrList(43130,"Po ตาก","หนองคาย"));
        list.add(new AddrList(43120,"Rattana Wapi","หนองคาย"));
        list.add(new AddrList(43160,"Sang Khom","หนองคาย"));
        list.add(new AddrList(43150,"Seka","หนองคาย"));
        list.add(new AddrList(43130,"Si เชียงราย","หนองคาย"));
        list.add(new AddrList(43210,"Si Wilai","หนองคาย"));
        list.add(new AddrList(43170,"So Phisai","หนองคาย"));
        list.add(new AddrList(43100,"Sra Khai","หนองคาย"));
        list.add(new AddrList(43110,"Tha Bo","หนองคาย"));
        list.add(new AddrList(11110,"Bang Bua Thong","นนทบุรี"));
        list.add(new AddrList(11130,"Bang Kruai","นนทบุรี"));
        list.add(new AddrList(11140,"Bang Yai","นนทบุรี"));
        list.add(new AddrList(11000,"เมืองนนทบุรี","นนทบุรี"));
        list.add(new AddrList(11120,"Pak Kret","นนทบุรี"));
        list.add(new AddrList(11150,"Sai Noi","นนทบุรี"));
        list.add(new AddrList(12120,"Khlong Luang","ปทุมธานี"));
        list.add(new AddrList(12150,"Lam Luk Ka","ปทุมธานี"));
        list.add(new AddrList(12140,"Lat Lum Kaeo","ปทุมธานี"));
        list.add(new AddrList(12000,"เมืองปทุมธานี","ปทุมธานี"));
        list.add(new AddrList(12170,"Nong Sua","ปทุมธานี"));
        list.add(new AddrList(12160,"Sam Khok","ปทุมธานี"));
        list.add(new AddrList(12110,"Thanyaburi","ปทุมธานี"));
        list.add(new AddrList(94120,"Khok Pho","ปัตตานี"));
        list.add(new AddrList(94230,"Kpho","ปัตตานี"));
        list.add(new AddrList(94180,"Mae Lan","ปัตตานี"));
        list.add(new AddrList(94220,"Mai Kaen","ปัตตานี"));
        list.add(new AddrList(94140,"Mayo","ปัตตานี"));
        list.add(new AddrList(94000,"เมืองปัตตานี","ปัตตานี"));
        list.add(new AddrList(94170,"Nong Chik","ปัตตานี"));
        list.add(new AddrList(94130,"Panare","ปัตตานี"));
        list.add(new AddrList(94110,"Sai Buri","ปัตตานี"));
        list.add(new AddrList(94140,"Thung Yan Daeng","ปัตตานี"));
        list.add(new AddrList(94160,"Yarang","ปัตตานี"));
        list.add(new AddrList(94150,"Yaring","ปัตตานี"));
        list.add(new AddrList(82170,"กะปง","พังงา"));
        list.add(new AddrList(82150,"คุระบุรี","พังงา"));
        list.add(new AddrList(82160,"เกาะยาว","พังงา"));
        list.add(new AddrList(82000,"เมืองพังงา","พังงา"));
        list.add(new AddrList(82110,"ตะกั่วป่า","พังงา"));
        list.add(new AddrList(82130,"ตะกั่วทุ่ง","พังงา"));
        list.add(new AddrList(82120,"ท้ายเหมือง","พังงา"));
        list.add(new AddrList(82180,"ทับปุด","พังงา"));
        list.add(new AddrList(93140,"Bang Kaeo","พัทลุง"));
        list.add(new AddrList(93130,"Khao Chaison","พัทลุง"));
        list.add(new AddrList(93110,"Khuan Khanun","พัทลุง"));
        list.add(new AddrList(93180,"Kong Ra","พัทลุง"));
        list.add(new AddrList(93000,"เมืองพัทลุง","พัทลุง"));
        list.add(new AddrList(93170,"Pa Bon","พัทลุง"));
        list.add(new AddrList(93110,"Pa Payam","พัทลุง"));
        list.add(new AddrList(93120,"Pak Phayun","พัทลุง"));
        list.add(new AddrList(93190,"Si Ban Phot","พัทลุง"));
        list.add(new AddrList(93000,"Sri Nakharin","พัทลุง"));
        list.add(new AddrList(93160,"Tamot","พัทลุง"));
        list.add(new AddrList(56160,"Chiacg Muan","พะเยา"));
        list.add(new AddrList(56110,"Chiang Kham","พะเยา"));
        list.add(new AddrList(56150,"Chun","พะเยา"));
        list.add(new AddrList(56120,"Dok Kham Tai","พะเยา"));
        list.add(new AddrList(56130,"Mae Chai","พะเยา"));
        list.add(new AddrList(56000,"เมืองพะเยา","พะเยา"));
        list.add(new AddrList(56140,"Pong","พะเยา"));
        list.add(new AddrList(56000,"Pu Khamyaw","พะเยา"));
        list.add(new AddrList(56110,"Pu Sang","พะเยา"));
        list.add(new AddrList(67160,"Bung Sam Phan","เพชรบูรณ์"));
        list.add(new AddrList(67150,"Chon Daen","เพชรบูรณ์"));
        list.add(new AddrList(67270,"Khao Kho","เพชรบูรณ์"));
        list.add(new AddrList(67120,"Lom Kao","เพชรบูรณ์"));
        list.add(new AddrList(67110,"Lom Sak","เพชรบูรณ์"));
        list.add(new AddrList(67000,"เมืองเพชรบูรณ์","เพชรบูรณ์"));
        list.add(new AddrList(67260,"Nam Nao","เพชรบูรณ์"));
        list.add(new AddrList(67140,"Nong Phai","เพชรบูรณ์"));
        list.add(new AddrList(67170,"Si Thep","เพชรบูรณ์"));
        list.add(new AddrList(67240,"Wang Pong","เพชรบูรณ์"));
        list.add(new AddrList(67130,"Wichian Buri","เพชรบูรณ์"));
        list.add(new AddrList(76110,"Ban Laem","เพชรบุรี"));
        list.add(new AddrList(76150,"Ban Lat","เพชรบุรี"));
        list.add(new AddrList(76120,"Cha-Am","เพชรบุรี"));
        list.add(new AddrList(76170,"Kang Krachan","เพชรบุรี"));
        list.add(new AddrList(76140,"Khao Yoi","เพชรบุรี"));
        list.add(new AddrList(76000,"เมืองเพชรบุรี","เพชรบุรี"));
        list.add(new AddrList(76160,"Nong Ya Plong","เพชรบุรี"));
        list.add(new AddrList(76130,"Tha Yang","เพชรบุรี"));
        list.add(new AddrList(66120,"Bang Mun Nak","พิจิตร"));
        list.add(new AddrList(66130,"Bung Norong","พิจิตร"));
        list.add(new AddrList(66210,"Dong Charoen","พิจิตร"));
        list.add(new AddrList(66000,"เมืองพิจิตร","พิจิตร"));
        list.add(new AddrList(66190,"Pho Prathap Chang","พิจิตร"));
        list.add(new AddrList(66130,"Pho Thale","พิจิตร"));
        list.add(new AddrList(66160,"Sak Lek","พิจิตร"));
        list.add(new AddrList(66140,"Sam Ngam","พิจิตร"));
        list.add(new AddrList(66150,"Tab Khlo","พิจิตร"));
        list.add(new AddrList(66110,"Taphan Hin","พิจิตร"));
        list.add(new AddrList(66140,"Wachirabarami","พิจิตร"));
        list.add(new AddrList(66180,"Wang Sai Phun","พิจิตร"));
        list.add(new AddrList(65110,"Bang Krathum","พิษณุโลก"));
        list.add(new AddrList(65140,"Bang Rakam","พิษณุโลก"));
        list.add(new AddrList(65170,"Chat Trakan","พิษณุโลก"));
        list.add(new AddrList(65000,"เมืองพิษณุโลก","พิษณุโลก"));
        list.add(new AddrList(65120,"Nakhon Thai","พิษณุโลก"));
        list.add(new AddrList(65190,"Noen Maprang","พิษณุโลก"));
        list.add(new AddrList(65150,"Phrom Phiram","พิษณุโลก"));
        list.add(new AddrList(65130,"Wอ่างทอง","พิษณุโลก"));
        list.add(new AddrList(65160,"Wat Bot","พิษณุโลก"));
        list.add(new AddrList(54140,"Den Chai","แพร่"));
        list.add(new AddrList(54150,"Long","แพร่"));
        list.add(new AddrList(54000,"เมืองแพร่","แพร่"));
        list.add(new AddrList(54170,"Nong Muangkhai","แพร่"));
        list.add(new AddrList(54140,"Rong Kwang","แพร่"));
        list.add(new AddrList(54120,"Song","แพร่"));
        list.add(new AddrList(54130,"Sung Men","แพร่"));
        list.add(new AddrList(54160,"Wang Chin","แพร่"));
        list.add(new AddrList(13240,"Ban แพร่k","พระนครศรีอยุธยา"));
        list.add(new AddrList(13250,"Bang Ban","พระนครศรีอยุธยา"));
        list.add(new AddrList(13160,"Bang Pa-In","พระนครศรีอยุธยา"));
        list.add(new AddrList(13220,"Bang Pahan","พระนครศรีอยุธยา"));
        list.add(new AddrList(13190,"Bang Sai","พระนครศรีอยุธยา"));
        list.add(new AddrList(13270,"Bang Sai","พระนครศรีอยุธยา"));
        list.add(new AddrList(13230,"Lat Bua Luang","พระนครศรีอยุธยา"));
        list.add(new AddrList(13150,"Maha Rat","พระนครศรีอยุธยา"));
        list.add(new AddrList(13260,"Nakhon Luang","พระนครศรีอยุธยา"));
        list.add(new AddrList(13120,"Pak Hai","พระนครศรีอยุธยา"));
        list.add(new AddrList(13140,"Phachi","พระนครศรีอยุธยา"));
        list.add(new AddrList(13000,"Pharnakhon Si Ayutthaya","พระนครศรีอยุธยา"));
        list.add(new AddrList(13110,"Sena","พระนครศรีอยุธยา"));
        list.add(new AddrList(13130,"Tha Rua","พระนครศรีอยุธยา"));
        list.add(new AddrList(13210,"Uthai","พระนครศรีอยุธยา"));
        list.add(new AddrList(13170,"Wang Noi","พระนครศรีอยุธยา"));
        list.add(new AddrList(83120,"กะทู้","ภูเก็ต"));
        list.add(new AddrList(83000,"เมืองภูเก็ต","ภูเก็ต"));
        list.add(new AddrList(83110,"ถลาง","ภูเก็ต"));
        list.add(new AddrList(25150,"Ban Sang","ปราจีนบุรี"));
        list.add(new AddrList(25110,"Kabin Buri","ปราจีนบุรี"));
        list.add(new AddrList(25190,"Khok Pip","ปราจีนบุรี"));
        list.add(new AddrList(25000,"เมืองปราจีนบุรี","ปราจีนบุรี"));
        list.add(new AddrList(25220,"Na Di","ปราจีนบุรี"));
        list.add(new AddrList(25130,"Prachanตากham","ปราจีนบุรี"));
        list.add(new AddrList(25140,"Si Maha Phot","ปราจีนบุรี"));
        list.add(new AddrList(25190,"Si Mahosot","ปราจีนบุรี"));
        list.add(new AddrList(77140,"Bang Saphan","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77170,"Bang Saphan Noi","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77110,"Hua Hin","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77150,"Kui Buri","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77000,"เมืองPrachuap Khirikan","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77120,"Pran Buri","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77180,"Samaroiyod","ประจวบคีรีขันธ์"));
        list.add(new AddrList(77130,"Thap Sakae","ประจวบคีรีขันธ์"));
        list.add(new AddrList(85120,"Kapoe","ระนอง"));
        list.add(new AddrList(85110,"Kra Buri","ระนอง"));
        list.add(new AddrList(85130,"La-Un","ระนอง"));
        list.add(new AddrList(85000,"เมืองระนอง","ระนอง"));
        list.add(new AddrList(85120,"Suk Samran","ระนอง"));
        list.add(new AddrList(70180,"Ban Ka","ราชบุรี"));
        list.add(new AddrList(70110,"Ban Pong","ราชบุรี"));
        list.add(new AddrList(70160,"Bang Phae","ราชบุรี"));
        list.add(new AddrList(70150,"Chom Bung","ราชบุรี"));
        list.add(new AddrList(70130,"Damnoen Saduak","ราชบุรี"));
        list.add(new AddrList(70000,"เมืองราชบุรี","ราชบุรี"));
        list.add(new AddrList(70140,"Pak Tho","ราชบุรี"));
        list.add(new AddrList(70120,"Photharam","ราชบุรี"));
        list.add(new AddrList(70180,"Suan Phung","ราชบุรี"));
        list.add(new AddrList(70170,"Wat Phleng","ราชบุรี"));
        list.add(new AddrList(21130,"Ban Chang","ระยอง"));
        list.add(new AddrList(21120,"Ban Khai","ระยอง"));
        list.add(new AddrList(21110,"Khao Chamao","ระยอง"));
        list.add(new AddrList(21110,"Klaeng","ระยอง"));
        list.add(new AddrList(21000,"เมืองระยอง","ระยอง"));
        list.add(new AddrList(21180,"Nikhom Pattana","ระยอง"));
        list.add(new AddrList(21140,"Pluak Daeng","ระยอง"));
        list.add(new AddrList(21210,"Wang Chan","ระยอง"));
        list.add(new AddrList(45160,"At Samat","ร้อยเอ็ด"));
        list.add(new AddrList(45000,"Chang Han","ร้อยเอ็ด"));
        list.add(new AddrList(45180,"Chaturaphak Phiman","ร้อยเอ็ด"));
        list.add(new AddrList(45000,"Chiang Khaw","ร้อยเอ็ด"));
        list.add(new AddrList(45150,"Kaset Wisai","ร้อยเอ็ด"));
        list.add(new AddrList(45250,"Moeiyawadi","ร้อยเอ็ด"));
        list.add(new AddrList(45000,"เมืองร้อยเอ็ด","ร้อยเอ็ด"));
        list.add(new AddrList(45220,"เมืองSuang","ร้อยเอ็ด"));
        list.add(new AddrList(45140,"Nong Hi","ร้อยเอ็ด"));
        list.add(new AddrList(45210,"Nong Phok","ร้อยเอ็ด"));
        list.add(new AddrList(45190,"Pathum Rat","ร้อยเอ็ด"));
        list.add(new AddrList(45140,"Phaanom Phrai","ร้อยเอ็ด"));
        list.add(new AddrList(45230,"Pho Chai","ร้อยเอ็ด"));
        list.add(new AddrList(45240,"Phon Sai","ร้อยเอ็ด"));
        list.add(new AddrList(45110,"Phon Thong","ร้อยเอ็ด"));
        list.add(new AddrList(45120,"Salaphum","ร้อยเอ็ด"));
        list.add(new AddrList(45000,"Sri Somdet","ร้อยเอ็ด"));
        list.add(new AddrList(45130,"Suwannaphum","ร้อยเอ็ด"));
        list.add(new AddrList(45170,"Thawatchaburi","ร้อยเอ็ด"));
        list.add(new AddrList(45170,"Tung Khaoluang","ร้อยเอ็ด"));
        list.add(new AddrList(27120,"Aranyaprathet","สระแก้ว"));
        list.add(new AddrList(27000,"Khao Chakhun","สระแก้ว"));
        list.add(new AddrList(27260,"Khlong Hat","สระแก้ว"));
        list.add(new AddrList(27120,"Khok Sung","สระแก้ว"));
        list.add(new AddrList(27000,"เมืองสระแก้ว","สระแก้ว"));
        list.add(new AddrList(27180,"Ta Phraya","สระแก้ว"));
        list.add(new AddrList(27120,"Wang Nam Yen","สระแก้ว"));
        list.add(new AddrList(27250,"Wang Sombun","สระแก้ว"));
        list.add(new AddrList(27160,"Wattana Nakhon","สระแก้ว"));
        list.add(new AddrList(47170,"Akat Amnuai","สกลนคร"));
        list.add(new AddrList(47140,"Ban Muang","สกลนคร"));
        list.add(new AddrList(47290,"Charoensin","สกลนคร"));
        list.add(new AddrList(47250,"Kham Ta Kla","สกลนคร"));
        list.add(new AddrList(47280,"Khok Si Supan","สกลนคร"));
        list.add(new AddrList(47210,"Kusuman","สกลนคร"));
        list.add(new AddrList(47180,"Kut Bak","สกลนคร"));
        list.add(new AddrList(47000,"เมืองสกลนคร","สกลนคร"));
        list.add(new AddrList(47270,"Nikhom Nam Un","สกลนคร"));
        list.add(new AddrList(47160,"Phang Khon","สกลนคร"));
        list.add(new AddrList(47130,"Phanna Nikhom","สกลนคร"));
        list.add(new AddrList(47180,"Phu Phan","สกลนคร"));
        list.add(new AddrList(47230,"Pon Nakaew","สกลนคร"));
        list.add(new AddrList(47110,"Sawang Daen Din","สกลนคร"));
        list.add(new AddrList(47190,"Song Dao","สกลนคร"));
        list.add(new AddrList(47260,"Tao Ngoi","สกลนคร"));
        list.add(new AddrList(47120,"Wanon Niwat","สกลนคร"));
        list.add(new AddrList(47150,"Waritchaphum","สกลนคร"));
        list.add(new AddrList(10560,"Bang Bo","สมุทรปราการ"));
        list.add(new AddrList(10540,"Bang Phli","สมุทรปราการ"));
        list.add(new AddrList(10540,"Bang Saotong","สมุทรปราการ"));
        list.add(new AddrList(10270,"เมืองสมุทรปราการ","สมุทรปราการ"));
        list.add(new AddrList(10130,"Phra Pradaeng","สมุทรปราการ"));
        list.add(new AddrList(10290,"Phra Samut Chedi","สมุทรปราการ"));
        list.add(new AddrList(74120,"Ban Phaeo","สมุทรสาคร"));
        list.add(new AddrList(74110,"Krathum Baen","สมุทรสาคร"));
        list.add(new AddrList(74000,"เมืองสมุทรสาคร","สมุทรสาคร"));
        list.add(new AddrList(75110,"Amphawa","สมุทรสงคราม"));
        list.add(new AddrList(75120,"Bang Khonthi","สมุทรสงคราม"));
        list.add(new AddrList(75000,"เมืองสมุทรสงคราม","สมุทรสงคราม"));
        list.add(new AddrList(18130,"Ban Mo","สระบุรี"));
        list.add(new AddrList(18000,"Chaloem Phakiat","สระบุรี"));
        list.add(new AddrList(18210,"Don Phut","สระบุรี"));
        list.add(new AddrList(18110,"Kaeng Khoi","สระบุรี"));
        list.add(new AddrList(18180,"Muak Lek","สระบุรี"));
        list.add(new AddrList(18000,"เมืองสระบุรี","สระบุรี"));
        list.add(new AddrList(18190,"Nong Doan","สระบุรี"));
        list.add(new AddrList(18140,"Nong Khae","สระบุรี"));
        list.add(new AddrList(18170,"Nong Saeng","สระบุรี"));
        list.add(new AddrList(18120,"Phra Phutthabat","สระบุรี"));
        list.add(new AddrList(18160,"Sao Hai","สระบุรี"));
        list.add(new AddrList(18220,"Wang Muang","สระบุรี"));
        list.add(new AddrList(18150,"Wihan Daeng","สระบุรี"));
        list.add(new AddrList(91160,"Khuan Doan","สตูล"));
        list.add(new AddrList(91130,"Khuan Ka Long","สตูล"));
        list.add(new AddrList(91110,"Langu","สตูล"));
        list.add(new AddrList(91130,"Manung","สตูล"));
        list.add(new AddrList(91000,"เมืองสตูล","สตูล"));
        list.add(new AddrList(91150,"Tha Phae","สตูล"));
        list.add(new AddrList(91120,"Thung Wa","สตูล"));
        list.add(new AddrList(16130,"Bang Rachan","สิงห์บุรี"));
        list.add(new AddrList(16110,"In Buri","สิงห์บุรี"));
        list.add(new AddrList(16150,"Khai Bang Rachan","สิงห์บุรี"));
        list.add(new AddrList(16000,"เมืองSing Buri","สิงห์บุรี"));
        list.add(new AddrList(16120,"Phrom Buri","สิงห์บุรี"));
        list.add(new AddrList(16140,"Tha Chang","สิงห์บุรี"));
        list.add(new AddrList(33110,"Benchalak","ศรีสะเกษ"));
        list.add(new AddrList(33220,"Bung Bun","ศรีสะเกษ"));
        list.add(new AddrList(33210,"Huai Thap Than","ศรีสะเกษ"));
        list.add(new AddrList(33110,"Kantharalak","ศรีสะเกษ"));
        list.add(new AddrList(33130,"Kanthararom","ศรีสะเกษ"));
        list.add(new AddrList(33140,"Khukhan","ศรีสะเกษ"));
        list.add(new AddrList(33150,"Khun Han","ศรีสะเกษ"));
        list.add(new AddrList(33120,"เมืองChan","ศรีสะเกษ"));
        list.add(new AddrList(33000,"เมืองศรีสะเกษ","ศรีสะเกษ"));
        list.add(new AddrList(33130,"Nam Kliang","ศรีสะเกษ"));
        list.add(new AddrList(33250,"Non Khun","ศรีสะเกษ"));
        list.add(new AddrList(33230,"Phayu","ศรีสะเกษ"));
        list.add(new AddrList(33180,"Phrai Bung","ศรีสะเกษ"));
        list.add(new AddrList(33120,"Po Sri Suwan","ศรีสะเกษ"));
        list.add(new AddrList(33170,"Prang Ku","ศรีสะเกษ"));
        list.add(new AddrList(33140,"Pu Sing","ศรีสะเกษ"));
        list.add(new AddrList(33160,"Rasi Salai","ศรีสะเกษ"));
        list.add(new AddrList(33240,"Si Rattana","ศรีสะเกษ"));
        list.add(new AddrList(33160,"Silalad","ศรีสะเกษ"));
        list.add(new AddrList(33120,"Uthumphon Phisai","ศรีสะเกษ"));
        list.add(new AddrList(33270,"Wang Hin","ศรีสะเกษ"));
        list.add(new AddrList(33190,"Yang Chum Noi","ศรีสะเกษ"));
        list.add(new AddrList(90110,"Bang Klam","สงขลา"));
        list.add(new AddrList(90130,"Chana","สงขลา"));
        list.add(new AddrList(90110,"Hat Yai","สงขลา"));
        list.add(new AddrList(90230,"Khlong Hoykhong","สงขลา"));
        list.add(new AddrList(90270,"Krasae Sin","สงขลา"));
        list.add(new AddrList(90220,"Kuan Niang","สงขลา"));
        list.add(new AddrList(90000,"เมืองสงขลา","สงขลา"));
        list.add(new AddrList(90310,"Na Mom","สงขลา"));
        list.add(new AddrList(90160,"Na Thawi","สงขลา"));
        list.add(new AddrList(90140,"Ranot","สงขลา"));
        list.add(new AddrList(90180,"Rattapum","สงขลา"));
        list.add(new AddrList(90120,"Sa Dao","สงขลา"));
        list.add(new AddrList(90210,"Sabayoi","สงขลา"));
        list.add(new AddrList(90190,"Sating Phra","สงขลา"));
        list.add(new AddrList(90330,"Singha Nakorn","สงขลา"));
        list.add(new AddrList(90150,"Thepha","สงขลา"));
        list.add(new AddrList(64140,"Ban Dan Lan Hoi","สุโขทัย"));
        list.add(new AddrList(64160,"Khiri Mat","สุโขทัย"));
        list.add(new AddrList(64170,"Kong Krailat","สุโขทัย"));
        list.add(new AddrList(64000,"เมืองสุโขทัย","สุโขทัย"));
        list.add(new AddrList(64110,"Sawankhalok","สุโขทัย"));
        list.add(new AddrList(64180,"Si Nakhon","สุโขทัย"));
        list.add(new AddrList(64120,"Si Samrong","สุโขทัย"));
        list.add(new AddrList(64130,"Si Satchanalai","สุโขทัย"));
        list.add(new AddrList(64150,"Thung Saliam","สุโขทัย"));
        list.add(new AddrList(72150,"Bang Pla Ma","สุพรรณบุรี"));
        list.add(new AddrList(72180,"Dan Chang","สุพรรณบุรี"));
        list.add(new AddrList(72120,"Doembang น่านgbuat","สุพรรณบุรี"));
        list.add(new AddrList(72170,"Don Chedi","สุพรรณบุรี"));
        list.add(new AddrList(72000,"เมืองSuphan Buri","สุพรรณบุรี"));
        list.add(new AddrList(72240,"Nong Yasai","สุพรรณบุรี"));
        list.add(new AddrList(72130,"Sam Chuk","สุพรรณบุรี"));
        list.add(new AddrList(72140,"Si Prachan","สุพรรณบุรี"));
        list.add(new AddrList(72110,"Song Phi Nong","สุพรรณบุรี"));
        list.add(new AddrList(72160,"U-Thong","สุพรรณบุรี"));
        list.add(new AddrList(84240,"Ban Na Doem","สุราษฎ์ธานี"));
        list.add(new AddrList(84120,"Ban Na San","สุราษฎ์ธานี"));
        list.add(new AddrList(84230,"Ban Ta Khun","สุราษฎ์ธานี"));
        list.add(new AddrList(84210,"Chai Buri","สุราษฎ์ธานี"));
        list.add(new AddrList(84110,"Chaiya","สุราษฎ์ธานี"));
        list.add(new AddrList(84220,"Don Sak","สุราษฎ์ธานี"));
        list.add(new AddrList(84160,"Kanchanadit","สุราษฎ์ธานี"));
        list.add(new AddrList(84260,"Khian Sa","สุราษฎ์ธานี"));
        list.add(new AddrList(84180,"Khiri Ratthanikhom","สุราษฎ์ธานี"));
        list.add(new AddrList(84280,"Ko Phangan","สุราษฎ์ธานี"));
        list.add(new AddrList(84140,"Ko Samui","สุราษฎ์ธานี"));
        list.add(new AddrList(84000,"เมืองสุราษฎ์ธานี","สุราษฎ์ธานี"));
        list.add(new AddrList(84250,"Phanom","สุราษฎ์ธานี"));
        list.add(new AddrList(84210,"Phrasaeng","สุราษฎ์ธานี"));
        list.add(new AddrList(84130,"Phunphin","สุราษฎ์ธานี"));
        list.add(new AddrList(84170,"Tha Chana","สุราษฎ์ธานี"));
        list.add(new AddrList(84150,"Tha Chang","สุราษฎ์ธานี"));
        list.add(new AddrList(84190,"Wiang Sa","สุราษฎ์ธานี"));
        list.add(new AddrList(84180,"Wiphawadi","สุราษฎ์ธานี"));
        list.add(new AddrList(63120,"Ban ตาก","ตาก"));
        list.add(new AddrList(63140,"Mae Ramat","ตาก"));
        list.add(new AddrList(63110,"Mae Sot","ตาก"));
        list.add(new AddrList(63000,"เมืองตาก","ตาก"));
        list.add(new AddrList(63160,"Phob Phra","ตาก"));
        list.add(new AddrList(63130,"Sam Ngao","ตาก"));
        list.add(new AddrList(63150,"Tha Song Yang","ตาก"));
        list.add(new AddrList(63170,"Umphang","ตาก"));
        list.add(new AddrList(63000,"Wang Chaw","ตาก"));
        list.add(new AddrList(92120,"Had Samran","ตรัง"));
        list.add(new AddrList(92130,"Huai Yot","ตรัง"));
        list.add(new AddrList(92110,"Kantang","ตรัง"));
        list.add(new AddrList(92000,"เมืองตรัง","ตรัง"));
        list.add(new AddrList(92170,"Na Yong","ตรัง"));
        list.add(new AddrList(92120,"Palian","ตรัง"));
        list.add(new AddrList(92160,"Rachada","ตรัง"));
        list.add(new AddrList(92150,"Sikao","ตรัง"));
        list.add(new AddrList(92220,"Wang Wiset","ตรัง"));
        list.add(new AddrList(92140,"Yan ตาก Kao","ตรัง"));
        list.add(new AddrList(23140,"Bo Rai","ตราด"));
        list.add(new AddrList(23130,"Khao Saming","ตราด"));
        list.add(new AddrList(23110,"Khlong Yai","ตราด"));
        list.add(new AddrList(23120,"Ko Chang","ตราด"));
        list.add(new AddrList(23000,"Ko Kud","ตราด"));
        list.add(new AddrList(23120,"Laem Ngob","ตราด"));
        list.add(new AddrList(23000,"เมืองตราด","ตราด"));
        list.add(new AddrList(34170 ,"Na Tan","อุบลราชธานี"));
        list.add(new AddrList(34230,"Buntharik","อุบลราชธานี"));
        list.add(new AddrList(34160,"Det Udom","อุบลราชธานี"));
        list.add(new AddrList(34000,"Don Moddang","อุบลราชธานี"));
        list.add(new AddrList(34170,"Khemarat","อุบลราชธานี"));
        list.add(new AddrList(34220,"Khong Chiam","อุบลราชธานี"));
        list.add(new AddrList(34150,"Khuang Nai","อุบลราชธานี"));
        list.add(new AddrList(34270,"Kut Khaopun","อุบลราชธานี"));
        list.add(new AddrList(34140,"เมืองSamsib","อุบลราชธานี"));
        list.add(new AddrList(34000,"เมืองอุบลราชธานี","อุบลราชธานี"));
        list.add(new AddrList(34280,"Na Chaluai","อุบลราชธานี"));
        list.add(new AddrList(41190,"Ban Dung","อดรธานี"));
        list.add(new AddrList(41190,"Ban Phu","อดรธานี"));
        list.add(new AddrList(41290,"Chaiwan","อดรธานี"));
        list.add(new AddrList(41130,"Ku Khaew","อดรธานี"));
        list.add(new AddrList(41110,"Kumphawapi","อดรธานี"));
        list.add(new AddrList(41250,"Kut Chab","อดรธานี"));
        list.add(new AddrList(41000,"เมืองอดรธานี","อดรธานี"));
        list.add(new AddrList(41380,"Na Yung","อดรธานี"));
        list.add(new AddrList(41210,"Nam Som","อดรธานี"));
        list.add(new AddrList(41240,"Non Sa-At","อดรธานี"));
        list.add(new AddrList(41130,"Nong Han","อดรธานี"));
        list.add(new AddrList(41340,"Nong Saeng","อดรธานี"));
        list.add(new AddrList(41220,"Nong Wua So","อดรธานี"));
        list.add(new AddrList(41150,"Phen","อดรธานี"));
        list.add(new AddrList(41110,"Phrachuk Siliakram","อดรธานี"));
        list.add(new AddrList(41130,"Pibun Rak","อดรธานี"));
        list.add(new AddrList(41260,"Sang Khom","อดรธานี"));
        list.add(new AddrList(41230,"Si That","อดรธานี"));
        list.add(new AddrList(41310,"Thung Fon","อดรธานี"));
        list.add(new AddrList(41380,"Wang Sam Mo","อดรธานี"));
        list.add(new AddrList(61140,"Ban Rai","อุทัยธานี"));
        list.add(new AddrList(61170,"Huai Khot","อุทัยธานี"));
        list.add(new AddrList(61160,"Lan Sak","อุทัยธานี"));
        list.add(new AddrList(61000,"เมืองอุทัยธานี","อุทัยธานี"));
        list.add(new AddrList(61110,"Nong Chang","อุทัยธานี"));
        list.add(new AddrList(61130,"Nong Khayang","อุทัยธานี"));
        list.add(new AddrList(61150,"Sawang Arom","อุทัยธานี"));
        list.add(new AddrList(61120,"Thap Than","อุทัยธานี"));
        list.add(new AddrList(53180,"Ban Khok","อุตรดิตถ์"));
        list.add(new AddrList(53160,"Fak Tha","อุตรดิตถ์"));
        list.add(new AddrList(53130,"Laplae","อุตรดิตถ์"));
        list.add(new AddrList(53000,"เมืองอุตรดิตถ์","อุตรดิตถ์"));
        list.add(new AddrList(53110,"Nam Pat","อุตรดิตถ์"));
        list.add(new AddrList(53120,"Phichai","อุตรดิตถ์"));
        list.add(new AddrList(53150,"Tha Pla","อุตรดิตถ์"));
        list.add(new AddrList(53230,"Tong Saen Khan","อุตรดิตถ์"));
        list.add(new AddrList(53140,"Tron","อุตรดิตถ์"));
        list.add(new AddrList(95130,"Banน่านg Sata","ยะลา"));
        list.add(new AddrList(95110,"Betong","ยะลา"));
        list.add(new AddrList(95120,"Ka Bung","ยะลา"));
        list.add(new AddrList(95000,"Kung Pinung","ยะลา"));
        list.add(new AddrList(95000,"เมืองยะลา","ยะลา"));
        list.add(new AddrList(95140,"Raman","ยะลา"));
        list.add(new AddrList(95150,"Raman","ยะลา"));
        list.add(new AddrList(95120,"Yaha","ยะลา"));
        list.add(new AddrList(35110,"Kham Khuan Kaeo","ยโสธร"));
        list.add(new AddrList(35160,"Kho Wang","ยโสธร"));
        list.add(new AddrList(35140,"Kud Chum","ยโสธร"));
        list.add(new AddrList(35120,"Loeng Nok Tha","ยโสธร"));
        list.add(new AddrList(35130,"Maha Chana Chai","ยโสธร"));
        list.add(new AddrList(35000,"เมืองยโสธร","ยโสธร"));
        list.add(new AddrList(35150,"Pa Tiu","ยโสธร"));
        list.add(new AddrList(35170,"Sai Mun","ยโสธร"));
        list.add(new AddrList(35120,"Thai Chaloen","ยโสธร"));
        return list;

    }

    public ArrayList<String> getProvinceList(){
        ArrayList<AddrList> addrLists = getAddrList();
        ArrayList<String> provinceList = new ArrayList<>();

        for (AddrList s : addrLists){
            if(!provinceList.contains(s.province)){
                provinceList.add(s.province);
            }
        }
        return provinceList;
    }
    public ArrayList<String> getDistrictList(String province){
        ArrayList<AddrList> addrLists = getAddrList();
        ArrayList<String> districtList = new ArrayList<>();

        for (AddrList s : addrLists){
            if(s.province.equals(province)){
                districtList.add(s.district);}
        }
        return districtList;
    }

    public ArrayList<String> getPostcodeList(String district){
        ArrayList<AddrList> addrLists = getAddrList();
        ArrayList<String> postcodeList = new ArrayList<>();

        for (AddrList s : addrLists){
            if(s.district.equals(district)){
            postcodeList.add(""+s.postcode);
            }
        }
        return postcodeList;
    }


}
